
## Date Apprenticeship Begins

**Required:** Yes

The date the apprenticeship begins. `Date Apprenticeship Begins` cannot before the program registration date. Dates starting with '0' zeros must be formatted as a text number.

## Apprentice First Name

**Required:** Yes

The first name of the apprentice.

## Apprentice Last Name

**Required:** Yes

The last name of the apprentice.

## Apprentice Middle Name

**Required:** No

The middle name of the apprentice.

## Apprentice Suffix

**Required:** No

The suffix to the apprentice name. Values include I, II, III, Jr., Sr.

## Social Security Number

**Required:** No

The Apprentice social security number. This value will be encrypted.

## Date of Birth

**Required:** Yes

The apprentice's date of birth. Apprentice must be 16 years old. Dates starting with '0' zeros must be formatted as a Text Number

## Gender

**Required:** Yes

'M' if the apprentice indicates that he is male. 'F' if the apprentice indicates that she is female. '9' if the apprentice did not self-identify.

## Employment Status

**Required:** Yes

Enter participant's employment status. Incumbent workers are defined as existing employees of the company.

## Apprentice Street Address

**Required:** Yes

The apprentice's street address.

## Apprentice City

**Required:** Yes

The apprentice's city.

## Apprentice State

**Required:** Yes

The apprentice's state.

## Apprentice 5-Digit Zip Code

**Required:** Yes

The apprentice's 5-digit zip code.

## Telephone

**Required:** No

The apprentice's telephone number.

## Email

**Required:** No

The apprentice's email address.

## Employer

**Required:** No

The unique identifier listed in the Employer tab for the Apprentice's Occupation. These identifiers are unique for each Employer listed.

## Ethnicity Hispanic / Latino

**Required:** Yes

If the apprentice indicates being a person of Cuban, Mexican, Puerto Rican, South or Central American, or other Spanish culture in origin, regardless of race, the value of this field is '1'. If the apprentice does not meet any of these conditions, the value of this field is '2'. If the apprentice does not self-identify ethnicity, the value of this field is '9'.

## Race-American Indian / Alaskan Native

**Required:** Yes

If the apprentice indicates origins in any of the original peoples of North America and South America (including Central America), and who maintains cultural identification through tribal affiliation or community recognition, the value of this field is '1'. If the apprentice does not meet any of these conditions, the value of this field is '0'. If the apprentice does not self-identify ethnicity, the value of this field is '9'.

## Asian

**Required:** Yes

If the apprentice indicates having origins in any of the original peoples of the Far East, Southeast Asia, or the Indian Subcontinent (e.g., India, Pakistan, Bangladesh, Sri Lanka, Nepal, Sikkim, and Bhutan), the value of this field is '1'. This area includes, for example, Cambodia, China, Japan, Korea, Malaysia, Pakistan, the Philippine Islands, Thailand, and Vietnam. If the apprentice does not meet any of these conditions, record '0'. If the apprentice does not self-identify ethnicity, the value of this field is '9'.

## Black / African American

**Required:** Yes

If the apprentice indicates having origins in any of the black racial groups of Africa, the value of this field is '1'. If the apprentice does not meet any of these conditions, the value of this field is '0'. If the apprentice does not self-identify ethnicity, the value of this field is '9'.

## Native Hawaiian / Other Pacific Islander

**Required:** Yes

If the apprentice indicates having origins in any of the original peoples of Hawaii, Guam, Samoa, or other Pacific Islands, the value of this field is '1'. If the apprentice does not meet any of these conditions, the value of this field is '0'. If the apprentice does not self-identify ethnicity, the value of this field is '9'.

## White

**Required:** Yes

If the apprentice indicates having origins in any of the original peoples of Europe, the Middle East, or North Africa, the value of this field is '1'. If the apprentice does not meet any of these conditions, the value of this field is '0'. If the apprentice does not self-identify ethnicity, the value of this field is '9'.

## Veteran Status

**Required:** Yes

If the apprentice indicates having served on active duty in the armed forces and who was discharged or released from such service under conditions other than dishonorable, the value of this field is '1'. If the apprentice does not meet any of these conditions, the value of this field is '0'. If the apprentice does not self-identify veteran status, the value of this field is '9'.

## Apprentice Disability Status

**Required:** Yes

If the apprentice indicates having any "disability," as defined in Section 3(2)(a) of the Americans with Disabilities Act of 1990 (42 U.S.C. 12102). Under that definition, a "disability" is a physical or mental impairment that substantially limits one or more of the person's major life activities. (For definitions and examples of "physical or mental impairment" and "major life activities," see paragraphs (1) and (2) of the definition of the term "disability" in 29 CFR 37.4, the definition section of the WIA non-discrimination regulations.), the value of this field is '1'. If the apprentice does not meet any of these conditions, the value of this field is '0'. If the apprentice does not self-identify disability status, the value of this field is '9'.

## Apprentice Education Level

**Required:** Yes

The Apprentice's education status.

## Occupation

**Required:** Yes

Enter the unique identifier listed in the Occupation tab for the apprentice's occupation. These identifiers are unique for each occupation listed.

## Related Technical Instruction Provider

**Required:** Yes

Enter the unique identifier listed in the RTI Providers tab for the apprentice's occupation. These identifiers are unique for each RTI Providers listed.

## Credit for previous experience

**Required:** No

Enter if any apprentice credit for previous experience (Note: If no credit is given, enter 0).

## Credit for Previous Related Training In Hours

**Required:** No

Enter apprentice credit for previous related training in hours (Note: If no credit is given, enter 0).

## Prior Wages

**Required:** Yes

Enter the apprentices hourly prior wage.

## Prior Wage Units

**Required:** Yes

Enter the apprentice prior wage units.

## Entry Wages

**Required:** Yes

Enter the apprentices hourly entry wage. This wage cannot be less than the apprentice hourly entry wage for the occupation.

## Entry Wage Units

**Required:** Yes

Enter the apprentice entry wage units.

## Wage Schedule

**Required:** Yes

Enter the unique identifier listed in the Wage Schedules tab for the apprentice's occupation. These identifiers are unique for each wage schedule listed.

## Previously Completed Career Lattice Levels

**Required:** No

Enter the unique identifier for all previously completed Career Lattice Levels (separated by a semicolon).

## Career Connection

**Required:** No

Enter the apprentice's career connection.

## WIOA Participant

**Required:** No

If WIOA Participant exists, record '1'. If no WIOA Participant exists, record '0'.

## Type

**Required:** No

Select the type.

## Career Linkage or Direct Entry

**Required:** No

Select the Career Linkage or Direct Entry types.

## TAA Participant

**Required:** No

If TAA Participant exists, record '1'. If no TAA Participant, record '0'.

## On-the-Job Training Funding Sources

**Required:** No

Enter if any on-the-job training funding sources.

## Student Status

**Required:** Yes

Enter the student status for SAA VA apprentice registration.

